USE [master]
GO

/****** Object:  Database [MyCheckList]    Script Date: 4/26/2022 11:41:59 AM ******/
CREATE DATABASE [MyCheckList]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyCheckList', FILENAME = N'C:\Users\Jesse Wang\MyCheckList.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyCheckList_log', FILENAME = N'C:\Users\Jesse Wang\MyCheckList_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyCheckList].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyCheckList] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyCheckList] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyCheckList] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyCheckList] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyCheckList] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyCheckList] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MyCheckList] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyCheckList] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyCheckList] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyCheckList] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyCheckList] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyCheckList] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyCheckList] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyCheckList] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyCheckList] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MyCheckList] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyCheckList] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyCheckList] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyCheckList] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyCheckList] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyCheckList] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MyCheckList] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyCheckList] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MyCheckList] SET  MULTI_USER 
GO

ALTER DATABASE [MyCheckList] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyCheckList] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyCheckList] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyCheckList] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyCheckList] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyCheckList] SET QUERY_STORE = OFF
GO

USE [MyCheckList]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [MyCheckList] SET  READ_WRITE 
GO

