//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCheckedListNet46.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckedItem
    {
        public int CheckedItemId { get; set; }
        public int ItemId { get; set; }
        public int MemberId { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
